{% set name = "aioinflux" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aioinflux-{{ version }}.tar.gz
  sha256: 720d056a9069ac3688f83b35786b234c890afb7c9a379eb421e5379e1eabc5cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aiohttp >=3.0
    - ciso8601

test:
  imports:
    - aioinflux
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gusutabopb/aioinflux
  summary: Asynchronous Python client for InfluxDB
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ktlim
